import { HandLandmarker, FaceLandmarker, FilesetResolver } from "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/vision_bundle.mjs";

const GESTURE_MEMES={
 rockstar:["memes/cat.jpg"],default:["memes/pokercat.jpg"],oneFingerUp:["memes/profcat.jpg","memes/professorcat.jpg"],fist:["memes/punchcat.jpg"],shhh:["memes/shhcat.jpg"],twoFingersTogether:["memes/uwucat.jpg","memes/uwucatt.jpg","memes/fingers together muehehe .jpg"],handCoverFace:["memes/hand cover face .jpg"],crashOutCat:["memes/crashout cat .jpg"],twoHandsOnHead:["memes/two hands on head .jpg"],handStretchedOut:["memes/hand stretched out, palm facing up .jpg"],sideEyeCat:["memes/side eye cat.jpg"],sideEyeDownCat:["memes/side eye.png"],mouthOpenCat:["memes/laugh and point .jpg"],huhCat:["memes/huh.png"],danceCat:["memes/two palms up.mov"],spinCat:["memes/spin cat.mov"]};
const VIDEO_GESTURES=new Set(["danceCat","spinCat"]);
const STABLE_FRAMES_REQUIRED=5,DEFAULT_FALLBACK_MS=600,FACE_STALE_MS=1200,SIDE_EYE_YAW_DEG=15,SIDE_EYE_DOWN_PITCH_DEG=12,EYE_WIDE_THRESHOLD=.01,HUH_JAW_THRESHOLD=.03,MOUTH_OPEN_JAW_THRESHOLD=.5;
const HAND_COVER_FACE_DIST_FACE_LOST=1.3,HAND_COVER_FACE_DIST_FACE_SEEN=.7;
const DANCE_TOP_ZONE_Y=.35,DANCE_BOTTOM_ZONE_Y=.65;
const video=document.getElementById("video"),memeImg=document.getElementById("memeImg"),memeVideo=document.getElementById("memeVideo"),hud=document.getElementById("debugHud"),statusEl=document.getElementById("status"),overlay=document.getElementById("overlay"),startBtn=document.getElementById("startBtn"),errorEl=document.getElementById("error"),memeLabel=document.getElementById("memeLabel");
let handLandmarker,faceLandmarker,lastVideoTime=-1,currentGesture="default",candidateGesture="default",candidateStreak=0,lastNonDefaultAt=performance.now(),lastFace=null,lastFaceSeenThisFrame=false,lastYawDebug=0,lastPitchDebug=0;
function vec(a,b){return{x:b.x-a.x,y:b.y-a.y,z:(b.z||0)-(a.z||0)}}function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y,(a.z||0)-(b.z||0))}function angleDeg(a,b){const d=a.x*b.x+a.y*b.y+a.z*b.z,m1=Math.hypot(a.x,a.y,a.z),m2=Math.hypot(b.x,b.y,b.z);if(m1<1e-9||m2<1e-9)return 180;return Math.acos(Math.min(1,Math.max(-1,d/(m1*m2))))*180/Math.PI}
function fingerExtended(lm,mcp,pip,tip){return angleDeg(vec(lm[mcp],lm[pip]),vec(lm[pip],lm[tip]))<45}
function yawFromMatrix(d){const r00=d[0],r10=d[4],r20=d[8],sy=Math.hypot(r00,r10);return sy<1e-6?0:Math.atan2(-r20,sy)*180/Math.PI}
function pitchFromMatrix(d){const r21=d[9],r22=d[10];return Math.atan2(r21,r22)*180/Math.PI}
function classifyHand(lm){const scale=dist(lm[0],lm[9])||1e-6;const indexUp=fingerExtended(lm,5,6,8),middleUp=fingerExtended(lm,9,10,12),ringUp=fingerExtended(lm,13,14,16),pinkyUp=fingerExtended(lm,17,18,20);const thumbOut=dist(lm[4],lm[17])/scale>1.25;return{indexUp,middleUp,ringUp,pinkyUp,thumbOut,curledCount:[indexUp,middleUp,ringUp,pinkyUp].filter(x=>!x).length,handScale:scale,indexTip:lm[8],wrist:lm[0],palmCenter:lm[9]}}
function blendshapeScores(r){if(!r.faceBlendshapes?.length)return{};return Object.fromEntries(r.faceBlendshapes[0].map(b=>[b.categoryName,b.score]))}
function eyeWide(s){return Math.max(s.eyeWideLeft||0,s.eyeWideRight||0)}
function updateFace(r){const now=performance.now(),saw=!!r.faceLandmarks?.length;lastFaceSeenThisFrame=saw;if(saw){const f=r.faceLandmarks[0],upper=f[13],lower=f[14],right=f[234],left=f[454],mouthCenter={x:(upper.x+lower.x)/2,y:(upper.y+lower.y)/2,z:((upper.z||0)+(lower.z||0))/2},faceWidth=dist(right,left);let yaw=0,pitch=0;if(r.facialTransformationMatrixes?.length){const d=r.facialTransformationMatrixes[0].data;yaw=yawFromMatrix(d);pitch=pitchFromMatrix(d)}lastYawDebug=yaw;lastPitchDebug=pitch;lastFace={mouthCenter,faceWidth,yawDeg:yaw,pitchDeg:pitch,t:now,blend:blendshapeScores(r)}}}
function isPointing(h){return h.indexUp&&!h.middleUp&&!h.ringUp&&!h.pinkyUp}
function decideGesture(hr){const now=performance.now(),fresh=!!lastFace&&now-lastFace.t<FACE_STALE_MS;
 if(!hr.landmarks?.length){if(fresh&&Math.abs(lastFace.yawDeg)>SIDE_EYE_YAW_DEG)return"sideEyeCat";return"default"}
 const hands=hr.landmarks.map(classifyHand);
 if(hands.length===2){if(isPointing(hands[0])&&isPointing(hands[1])){const s=(hands[0].handScale+hands[1].handScale)/2;if(dist(hands[0].indexTip,hands[1].indexTip)/s<1.4)return"twoFingersTogether"}
  if(fresh){const{mouthCenter,faceWidth}=lastFace;if(hands.every(h=>dist(h.palmCenter,mouthCenter)/faceWidth<2.2)){const headTop=mouthCenter.y-faceWidth*1.1;if(hands.every(h=>h.palmCenter.y<headTop))return"twoHandsOnHead";return"crashOutCat"}}
  const ys=hands.map(h=>h.palmCenter.y),open=hands.every(h=>h.curledCount===0);if(open&&ys.some(y=>y<DANCE_TOP_ZONE_Y)&&ys.some(y=>y>DANCE_BOTTOM_ZONE_Y))return"danceCat";
 }
 const h=hands[0];if(h.curledCount===4)return"fist";if(h.thumbOut&&h.pinkyUp&&!h.indexUp&&!h.middleUp&&!h.ringUp)return"rockstar";
 if(isPointing(h)){if(fresh&&dist(h.indexTip,lastFace.mouthCenter)/lastFace.faceWidth<.55)return"shhh";return"oneFingerUp"}
 if(fresh){const d=dist(h.palmCenter,lastFace.mouthCenter)/lastFace.faceWidth;if(d<(lastFaceSeenThisFrame?HAND_COVER_FACE_DIST_FACE_SEEN:HAND_COVER_FACE_DIST_FACE_LOST))return"handCoverFace"}
 if(h.curledCount===0)return"handStretchedOut";
 if(fresh){const b=lastFace.blend||{};if((b.jawOpen||0)>HUH_JAW_THRESHOLD&&eyeWide(b)>EYE_WIDE_THRESHOLD)return"huhCat";if((b.jawOpen||0)>MOUTH_OPEN_JAW_THRESHOLD)return"mouthOpenCat";if(Math.abs(lastFace.yawDeg)>SIDE_EYE_YAW_DEG)return"sideEyeCat";if(lastFace.pitchDeg>SIDE_EYE_DOWN_PITCH_DEG&&Math.abs(lastFace.yawDeg)>5)return"sideEyeDownCat"}
 return"default"}
function pick(g){const a=GESTURE_MEMES[g]||GESTURE_MEMES.default;return a[Math.floor(Math.random()*a.length)]}
function applyGesture(g){if(g===currentGesture)return;currentGesture=g;const src=pick(g);memeLabel.textContent=g.toUpperCase();if(VIDEO_GESTURES.has(g)){memeImg.classList.add("hidden");memeVideo.classList.remove("hidden");memeVideo.src=src;memeVideo.currentTime=0;memeVideo.play().catch(()=>{});}else{memeVideo.pause();memeVideo.removeAttribute("src");memeVideo.load();memeVideo.classList.add("hidden");memeImg.classList.remove("hidden");memeImg.src=src}}
function hudUpdate(){hud.textContent=`gesture: ${currentGesture}\nyaw: ${lastYawDebug>=0?"+":""}${lastYawDebug.toFixed(1)}°  (±${SIDE_EYE_YAW_DEG}°)\npitch: ${lastPitchDebug>=0?"+":""}${lastPitchDebug.toFixed(1)}°`}
async function init(){statusEl.textContent="Modellek betöltése…";const fileset=await FilesetResolver.forVisionTasks("https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/wasm");handLandmarker=await HandLandmarker.createFromOptions(fileset,{baseOptions:{modelAssetPath:"https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task",delegate:"GPU"},runningMode:"VIDEO",numHands:2});faceLandmarker=await FaceLandmarker.createFromOptions(fileset,{baseOptions:{modelAssetPath:"https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task",delegate:"GPU"},runningMode:"VIDEO",numFaces:1,outputFacialTransformationMatrixes:true,outputFaceBlendshapes:true});const stream=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720},facingMode:"user"},audio:false});video.srcObject=stream;await video.play();overlay.classList.add("hidden");statusEl.textContent="Kamera aktív";requestAnimationFrame(loop)}
function loop(){const now=performance.now();if(video.currentTime!==lastVideoTime&&handLandmarker&&faceLandmarker){lastVideoTime=video.currentTime;const hr=handLandmarker.detectForVideo(video,now),fr=faceLandmarker.detectForVideo(video,now);updateFace(fr);const g=decideGesture(hr);if(g===candidateGesture)candidateStreak++;else{candidateGesture=g;candidateStreak=1}if(candidateStreak>=STABLE_FRAMES_REQUIRED)applyGesture(g);if(g!=="default")lastNonDefaultAt=now;if(now-lastNonDefaultAt>DEFAULT_FALLBACK_MS&&currentGesture!=="default")applyGesture("default");hudUpdate()}requestAnimationFrame(loop)}
startBtn.addEventListener("click",async()=>{startBtn.disabled=true;errorEl.textContent="";try{await init()}catch(e){console.error(e);statusEl.textContent="Kamera hiba";errorEl.textContent="Nem sikerült elindítani a kamerát.\n\n"+(e?.message||e);startBtn.disabled=false}});
